[project]
name = "dhivehi-benchmark"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
]
